version: '3.8'

services:
  medical-ct-analysis:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    restart: unless-stopped
    container_name: medical-ct-web
    
  # 可选：添加nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - medical-ct-analysis
    restart: unless-stopped
    container_name: medical-ct-nginx 